$VirtualSwitchName = "External"

LINUX_IMAGE = "bento/ubuntu-16.04"

Vagrant.configure("2") do |config|
    config.vm.provider "hyperv" do |h|
        h.enable_virtualization_extensions = true
        h.linked_clone = true
        h.cpus = 4
        h.memory = 4096
        h.maxmemory = 4096
        h.vmname = "k8s-dev"
    end
    config.vm.define "k8s-dev" do |subconfig|
        subconfig.vm.box = LINUX_IMAGE
        subconfig.vm.hostname = "k8s-dev"
        subconfig.vm.network :public_network, bridge: $VirtualSwitchName
        config.vm.synced_folder ".", "/vagrant", disabled: true
        subconfig.vm.provision "shell", path: "ubuntu.sh"
        subconfig.vm.provision "shell", path: "go.sh"
    end
end